name: voice_email_assistant
description: A Flutter application designed for visually impaired users that enables full voice-based email management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  local_auth: ^2.1.7
  flutter_tts: ^3.8.5
  speech_to_text: ^6.1.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.2
  provider: ^6.1.1
  supabase_flutter: ^2.0.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  url_launcher: ^6.2.2
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
