name: attendance_app
description: University attendance system using facial recognition
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State management
  provider: ^6.0.5
  # Network and storage
  http: ^1.1.0
  shared_preferences: ^2.2.0
  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  # Camera and ML
  camera: ^0.10.5+3
  google_mlkit_face_detection: ^0.8.0
  # Network connectivity
  connectivity_plus: ^4.0.2
  # Others
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  csv: ^5.0.2
  file_picker: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
